package org.example;

public class ModelData {
    private String[] values = {
            "af-ZA,Afrikaans",
            "sq-AL,Albanian",
            "am-ET,Amharic",
            "ar-SA,Arabic",
            "hy-AM,Armenian",
            "az-AZ,Azerbaijani",
            "bjs-BB,Bajan",
            "rm-RO,Balkan Gipsy",
            "eu-ES,Basque",
            "bem-ZM,Bemba",
            "bn-IN,Bengali",
            "be-BY,Bielarus",
            "bi-VU,Bislama",
            "bs-BA,Bosnian",
            "br-FR,Breton",
            "bg-BG,Bulgarian",
            "my-MM,Burmese",
            "ca-ES,Catalan",
            "da-DK,Danish",
            "de-DE,German",
            "dz-BT,Dzongkha",
            "en-US,English",
            "eo-EO,Esperanto",
            "et-EE,Estonian",
            "ee-GH,Ewe",
            "fj-FJ,Fijian",
            "fi-FI,Finnish",
            "fr-FR,French",
            "fo-FO,Frisian",
            "gl-ES,Gallegan",
            "ka-GE,Georgian",
            "el-GR,Greek",
            "gn-PY,Guarani",
            "gu-IN,Gujarati",
            "ht-HT,Haitian Creole",
            "ha-NG,Hausa",
            "he-IL,Hebrew",
            "hi-IN,Hindi",
            "hu-HU,Hungarian",
            "is-IS,Icelandic",
            "id-ID,Indonesian",
            "ia-UN,Interlingua",
            "ga-IE,Irish",
            "it-IT,Italian",
            "ja-JP,Japanese",
            "jv-ID,Javanese",
            "kn-IN,Kannada",
            "ks-IN,Kashmiri",
            "kk-KZ,Kazakh",
            "km-KH,Khmer",
            "rw-RW,Kinyarwanda",
            "rn-BI,Kirundi",
            "ko-KR,Korean",
            "ku-TR,Kurdish",
            "ky-KG,Kyrgyz",
            "lo-LA,Lao",
            "lv-LV,Latvian",
            "lt-LT,Lithuanian",
            "lu-CD,Luba-Katanga",
            "lb-LU,Luxembourgish",
            "mk-MK,Macedonian",
            "mg-MG,Malagasy",
            "ms-MY,Malay",
            "ml-IN,Malayalam",
            "mt-MT,Maltese",
            "gv-IM,Manx",
            "mr-IN,Marathi",
            "mh-MH,Marshallese",
            "mn-MN,Mongolian",
            "ne-NP,Nepali",
            "nn-NO,Norwegian Nynorsk",
            "no-NO,Norwegian",
            "oc-FR,Occitan",
            "or-IN,Oriya",
            "om-ET,Oromo",
            "ps-AF,Pashto",
            "fa-IR,Persian",
            "pl-PL,Polish",
            "pt-BR,Portuguese",
            "pa-IN,Punjabi",
            "qu-PE,Quechua",
            "ro-RO,Romanian",
            "ro-MD,Moldavian",
            "sa-IN,Sanskrit",
            "gd-GB,Scots Gaelic",
            "sr-SP,Serbian",
            "si-LK,Sinhalese",
            "sk-SK,Slovak",
            "sl-SI,Slovenian",
            "so-SO,Somali",
            "es-ES,Spanish",
            "su-ID,Sundanese",
            "sw-TZ,Swahili",
            "sv-SE,Swedish",
            "tl-PH,Tagalog",
            "tg-TJ,Tajik",
            "tz-MA,Tamazight",
            "ta-IN,Tamil",
            "te-IN,Telugu",
            "th-TH,Thai",
            "ti-ER,Tigrinya",
            "to-TO,Tongan",
            "tr-TR,Turkish",
            "tk-TM,Turkmen",
            "ug-CN,Uighur",
            "uk-UA,Ukrainian",
            "ur-PK,Urdu",
            "uz-UZ,Uzbek",
            "ve-ZA,Venda",
            "vi-VN,Vietnamese",
            "cy-GB, Welsh",
            "fy-NL, Western Frisian",
            "xh-ZA, Xhosa",
            "yo-NG, Yoruba",
            "zu-ZA, Zulu",
    };


    void getData(){
        for (String data : values){
            System.out.println(data);
        }
    }
}
